<a href="https://colab.research.google.com/github/riyapalesha/SPPU-Data_Science_And_Big_Data_Analytics_Lab/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Wrangling I
Perform the following operations using Python on any open source dataset (e.g., data.csy)
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g. https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas data frame.
4. Data Preprocessing: check for missing values in the data using pandas insult, describe function to get some initial statistics. Provide variable descriptions. Types of variables etc. Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set. If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.
In addition to the codes and outputs, explain every operation that you do in the above steps and explain everything that you do to import/read/scrape the data set.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Salaries.csv to Salaries (1).csv


In [ ]:
#importing python libraries
import numpy as np
import pandas as pd

In [ ]:
# Reading dataset from csv file
orig_df=pd.read_csv("Salaries.csv")
orig_df

<ipython-input-16-db868827a193>:2: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  orig_df=pd.read_csv("Salaries.csv")


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [ ]:
# Creating a deepcopy of the dataframe
df=orig_df.copy()
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [ ]:
# Displaying first 5 records
df.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [ ]:
# Displaying first 10 records
df.head(10)

Id        EmployeeName                                        JobTitle  \
0   1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5   6      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   
6   7           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   
7   8       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS   
8   9      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)   
9  10  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   
5   118602.0      8601.0  189082.74      NaN  316285.74         316285.74   
6   92492.01     89062.9  134426.14      NaN  315981.05         315981.05   
7  256576.96         0.0    51322.5      NaN  307899.46         307899.46   
8  176932.64    86362.68   40132.23      NaN  303427.55         303427.55   
9   285262.0         0.0   17115.73      NaN  302377.73         302377.73   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN  
5  2011    NaN  San Francisco    NaN  
6  2011    NaN  San Francisco    NaN  
7  2011    NaN  San Francisco    NaN  
8  2011    NaN  San Francisco    NaN  
9  2011    NaN  San Francisco    NaN

In [ ]:
# Displaying last 5 records
df.tail()

Id   EmployeeName                    JobTitle       BasePay  \
148649  148650  Roy I Tillery                   Custodian          0.00   
148650  148651   Not provided                Not provided  Not Provided   
148651  148652   Not provided                Not provided  Not Provided   
148652  148653   Not provided                Not provided  Not Provided   
148653  148654      Joe Lopez  Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits  TotalPay  TotalPayBenefits  \
148649          0.00          0.00          0.00      0.00              0.00   
148650  Not Provided  Not Provided  Not Provided      0.00              0.00   
148651  Not Provided  Not Provided  Not Provided      0.00              0.00   
148652  Not Provided  Not Provided  Not Provided      0.00              0.00   
148653          0.00       -618.13          0.00   -618.13           -618.13   

        Year  Notes         Agency Status  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT

In [ ]:
# Displaying last 10 records
df.tail(10)

Id      EmployeeName                      JobTitle       BasePay  \
148644  148645      Randy D Winn  Stationary Eng, Sewage Plant          0.00   
148645  148646  Carolyn A Wilson     Human Services Technician          0.00   
148646  148647      Not provided                  Not provided  Not Provided   
148647  148648    Joann Anderson   Communications Dispatcher 2          0.00   
148648  148649       Leon Walker                     Custodian          0.00   
148649  148650     Roy I Tillery                     Custodian          0.00   
148650  148651      Not provided                  Not provided  Not Provided   
148651  148652      Not provided                  Not provided  Not Provided   
148652  148653      Not provided                  Not provided  Not Provided   
148653  148654         Joe Lopez    Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits  TotalPay  TotalPayBenefits  \
148644          0.00          0.00          0.00      0.00              0.00   
148645          0.00          0.00          0.00      0.00              0.00   
148646  Not Provided  Not Provided  Not Provided      0.00              0.00   
148647          0.00          0.00          0.00      0.00              0.00   
148648          0.00          0.00          0.00      0.00              0.00   
148649          0.00          0.00          0.00      0.00              0.00   
148650  Not Provided  Not Provided  Not Provided      0.00              0.00   
148651  Not Provided  Not Provided  Not Provided      0.00              0.00   
148652  Not Provided  Not Provided  Not Provided      0.00              0.00   
148653          0.00       -618.13          0.00   -618.13           -618.13   

        Year  Notes         Agency Status  
148644  2014    NaN  San Francisco     PT  
148645  2014    NaN  San Francisco     PT  
148646  2014    NaN  San Francisco    NaN  
148647  2014    NaN  San Francisco     PT  
148648  2014    NaN  San Francisco     PT  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT

In [ ]:
# Basic statistical details
df.describe()

Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

In [ ]:
df.describe(include="object")

EmployeeName          JobTitle   BasePay  OvertimePay  OtherPay  \
count        148654            148654  148049.0     148654.0  148654.0   
unique       110811              2159  109900.0      66555.0   84968.0   
top       Kevin Lee  Transit Operator       0.0          0.0       0.0   
freq             13              7036     875.0      66103.0   35218.0   

        Benefits         Agency Status  
count   112495.0         148654  38119  
unique   99635.0              1      2  
top          0.0  San Francisco     FT  
freq      1053.0         148654  22334

In [ ]:
# Return a tuple representing the dimensionality of the dataset
df.shape

(148654, 13)

In [ ]:
missing_values=df.isnull()
missing_values

Id  EmployeeName  JobTitle  BasePay  OvertimePay  OtherPay  \
0       False         False     False    False        False     False   
1       False         False     False    False        False     False   
2       False         False     False    False        False     False   
3       False         False     False    False        False     False   
4       False         False     False    False        False     False   
...       ...           ...       ...      ...          ...       ...   
148649  False         False     False    False        False     False   
148650  False         False     False    False        False     False   
148651  False         False     False    False        False     False   
148652  False         False     False    False        False     False   
148653  False         False     False    False        False     False   

        Benefits  TotalPay  TotalPayBenefits   Year  Notes  Agency  Status  
0           True     False             False  False   True   False    True  
1           True     False             False  False   True   False    True  
2           True     False             False  False   True   False    True  
3           True     False             False  False   True   False    True  
4           True     False             False  False   True   False    True  
...          ...       ...               ...    ...    ...     ...     ...  
148649     False     False             False  False   True   False   False  
148650     False     False             False  False   True   False    True  
148651     False     False             False  False   True   False    True  
148652     False     False             False  False   True   False    True  
148653     False     False             False  False   True   False   False  

[148654 rows x 13 columns]

In [ ]:
missing_values_count=df.isnull().sum()
missing_values_count

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [ ]:
variable_datatypes=df.dtypes
variable_datatypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay              object
OvertimePay          object
OtherPay             object
Benefits             object
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status               object
dtype: object

In [ ]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

#Handling missing values and Inconsistencies

In [ ]:
df["BasePay"].unique()

array([167411.18, 155966.02, 212739.13, ..., '6.04', '15.50',
       'Not Provided'], dtype=object)

In [ ]:
df["BasePay"].replace("Not Provided", np.nan, inplace=True)
# BasePay as datatype as object
# Converting the datatype to float
df["BasePay"]=df["BasePay"].astype(float)
df["BasePay"].dtype

dtype('float64')

In [ ]:
# Checking that Not Provided cells have become missing values
df["BasePay"].unique()

array([1.6741118e+05, 1.5596602e+05, 2.1273913e+05, ..., 1.7260000e+01,
       6.0400000e+00, 1.5500000e+01])

In [ ]:
df["OvertimePay"].unique()

array([0.0, 245131.88, 106088.18, ..., '102.70', '56.77', 'Not Provided'],
      dtype=object)

In [ ]:
df["OvertimePay"].replace("Not Provided", np.nan, inplace=True)
df["OvertimePay"]=df["OvertimePay"].astype(float)
df["OvertimePay"].dtype

dtype('float64')

In [ ]:
df["OvertimePay"].unique()

array([0.0000000e+00, 2.4513188e+05, 1.0608818e+05, ..., 1.0270000e+02,
       5.6770000e+01,           nan])

In [ ]:
df["OtherPay"].unique()

array([400184.25, 137811.38, 16452.6, ..., '13.35', 'Not Provided',
       '-618.13'], dtype=object)

In [ ]:
df["OtherPay"].replace("Not Provided", np.nan, inplace=True)
df["OtherPay"]=df["OtherPay"].astype(float)
df["OtherPay"].dtype

dtype('float64')

In [ ]:
df["OtherPay"].unique()

array([ 4.0018425e+05,  1.3781138e+05,  1.6452600e+04, ...,
        1.5350000e+01,            nan, -6.1813000e+02])

In [ ]:
df["Agency"].unique()

array(['San Francisco'], dtype=object)

In [ ]:
df["Agency"]=df["Agency"].astype('|S')

astype(): This is a method available in both NumPy and Pandas that is used to cast or convert the data type of an array or a column to a specified type.

'|S': This specifies the target data type, which is a fixed-length string. The '|S' notation is specific to NumPy and is followed by a number indicating the desired length of the string. For example, '|S10' specifies a fixed-length string of length 10.

In [ ]:
# The datatype has been changed from object to string
df["Agency"].dtype

dtype('S13')

In [ ]:
df["Benefits"].unique()

array([         nan, 4.443012e+04, 6.981019e+04, ..., 2.200000e-01,
       1.300000e-01, 1.240000e+00])

In [ ]:
df["Benefits"]=df["Benefits"].astype(float)

In [ ]:
df.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency                 |S13
Status               object
dtype: object

**HANDLING MISSING VALUES**


There are several ways to handle records containing missing values (NaN) in a dataset. The choice of method depends on the specific context and the nature of the data. Here are some common approaches:

Dropping rows: Remove the rows that contain missing values. This approach is suitable when the missing values are limited and removing the affected rows does not significantly impact the analysis. You can use the dropna() method in Pandas with the subset parameter to specify the columns to consider when dropping rows.

Dropping columns: Remove entire columns that contain a large number of missing values or are irrelevant to the analysis. This approach is appropriate when the missing values are prevalent in specific columns and those columns do not provide meaningful information for the analysis. Use the dropna() method with the axis=1 parameter to drop columns.

Imputation: Replace missing values with estimated or calculated values. Imputation allows you to fill in the missing values based on various strategies. Common imputation techniques include replacing missing values with the mean, median, mode, or a constant value. The Pandas fillna() method can be used to fill missing values with a specific value or a calculated value.

In [ ]:
df.dropna(subset=["BasePay"], inplace=True)

In [ ]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148045
Agency                   0
Status              109926
dtype: int64

In [ ]:
df["Benefits"].fillna(df["Benefits"].median(), inplace=True)

In [ ]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits                 0
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148045
Agency                   0
Status              109926
dtype: int64

**Converting Categorical variables to Numerical**

In [ ]:
df["Status"].unique()

array([nan, 'PT', 'FT'], dtype=object)

In [ ]:
# Creating copy of df to apply label encoding (method 1)
df1=df.copy()

In [ ]:
df1.tail()

Id      EmployeeName                     JobTitle  BasePay  \
148645  148646  Carolyn A Wilson    Human Services Technician      0.0   
148647  148648    Joann Anderson  Communications Dispatcher 2      0.0   
148648  148649       Leon Walker                    Custodian      0.0   
148649  148650     Roy I Tillery                    Custodian      0.0   
148653  148654         Joe Lopez   Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148645          0.0      0.00       0.0      0.00              0.00  2014   
148647          0.0      0.00       0.0      0.00              0.00  2014   
148648          0.0      0.00       0.0      0.00              0.00  2014   
148649          0.0      0.00       0.0      0.00              0.00  2014   
148653          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes            Agency Status  
148645    NaN  b'San Francisco'     PT  
148647    NaN  b'San Francisco'     PT  
148648    NaN  b'San Francisco'     PT  
148649    NaN  b'San Francisco'     PT  
148653    NaN  b'San Francisco'     PT

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the categorical variable
encoded_status = label_encoder.fit_transform(df["Status"])
encoded_status

array([2, 2, 2, ..., 1, 1, 1])

In [ ]:
df1["Status"]=encoded_status

In [ ]:
df1.tail()

Id      EmployeeName                     JobTitle  BasePay  \
148645  148646  Carolyn A Wilson    Human Services Technician      0.0   
148647  148648    Joann Anderson  Communications Dispatcher 2      0.0   
148648  148649       Leon Walker                    Custodian      0.0   
148649  148650     Roy I Tillery                    Custodian      0.0   
148653  148654         Joe Lopez   Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148645          0.0      0.00       0.0      0.00              0.00  2014   
148647          0.0      0.00       0.0      0.00              0.00  2014   
148648          0.0      0.00       0.0      0.00              0.00  2014   
148649          0.0      0.00       0.0      0.00              0.00  2014   
148653          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes            Agency  Status  
148645    NaN  b'San Francisco'       1  
148647    NaN  b'San Francisco'       1  
148648    NaN  b'San Francisco'       1  
148649    NaN  b'San Francisco'       1  
148653    NaN  b'San Francisco'       1

In [ ]:
df1["Status"].isna().sum()

0

In [ ]:
df["Status"].isna().sum()

109926

get_dummies() method 2

the pd.get_dummies() function is used to convert the 'Category' column of the DataFrame df into multiple binary-encoded columns. Each unique category in the 'Category' column is represented by a separate column, where a value of 1 indicates the presence of that category in the original observation, and 0 indicates its absence.

The prefix parameter is used to add a prefix to the column names in the encoded DataFrame to distinguish them from the original column. In this case, the prefix 'Category' is added to the encoded columns.

In [ ]:
df_encoded=pd.get_dummies(df["Status"], prefix="Status")
df_encoded

Status_FT  Status_PT
0               0          0
1               0          0
2               0          0
3               0          0
4               0          0
...           ...        ...
148645          0          1
148647          0          1
148648          0          1
148649          0          1
148653          0          1

[148045 rows x 2 columns]

In [ ]:
df.drop('Status',axis=1, inplace=True)

In [ ]:
df=pd.concat([df,df_encoded] , axis=1)

In [ ]:
df.tail()

Id      EmployeeName                     JobTitle  BasePay  \
148645  148646  Carolyn A Wilson    Human Services Technician      0.0   
148647  148648    Joann Anderson  Communications Dispatcher 2      0.0   
148648  148649       Leon Walker                    Custodian      0.0   
148649  148650     Roy I Tillery                    Custodian      0.0   
148653  148654         Joe Lopez   Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148645          0.0      0.00       0.0      0.00              0.00  2014   
148647          0.0      0.00       0.0      0.00              0.00  2014   
148648          0.0      0.00       0.0      0.00              0.00  2014   
148649          0.0      0.00       0.0      0.00              0.00  2014   
148653          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes            Agency  Status_FT  Status_PT  
148645    NaN  b'San Francisco'          0          1  
148647    NaN  b'San Francisco'          0          1  
148648    NaN  b'San Francisco'          0          1  
148649    NaN  b'San Francisco'          0          1  
148653    NaN  b'San Francisco'          0          1

In [ ]:
df["Status_FT"].isna().sum()
df["Status_PT"].isna().sum()

0

**Data Normalization**
1. MinMax algorithm
2. Z score

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
column_values=df["BasePay"].values.reshape(-1,1)
normalized_values=scaler.fit_transform(column_values)
df["NormalizedBasePay"]=normalized_values

In [ ]:
df.tail()

Id      EmployeeName                     JobTitle  BasePay  \
148645  148646  Carolyn A Wilson    Human Services Technician      0.0   
148647  148648    Joann Anderson  Communications Dispatcher 2      0.0   
148648  148649       Leon Walker                    Custodian      0.0   
148649  148650     Roy I Tillery                    Custodian      0.0   
148653  148654         Joe Lopez   Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148645          0.0      0.00       0.0      0.00              0.00  2014   
148647          0.0      0.00       0.0      0.00              0.00  2014   
148648          0.0      0.00       0.0      0.00              0.00  2014   
148649          0.0      0.00       0.0      0.00              0.00  2014   
148653          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes            Agency  Status_FT  Status_PT  NormalizedBasePay  
148645    NaN  b'San Francisco'          0          1            0.00052  
148647    NaN  b'San Francisco'          0          1            0.00052  
148648    NaN  b'San Francisco'          0          1            0.00052  
148649    NaN  b'San Francisco'          0          1            0.00052  
148653    NaN  b'San Francisco'          0          1            0.00052

In [ ]:
# Min Max algorithm using formula
op_min=df["OvertimePay"].min()
op_max=df["OvertimePay"].max()


df["NormalizedOvertimePay"]=(df["OvertimePay"]-op_min)/(op_max-op_min)

In [ ]:
df["OtherPay"].dtype

dtype('float64')

In [ ]:
# Z-score normalization technique->(x - mean) / std

otherPay_mean = df["OtherPay"].mean()
otherPay_std = df["OtherPay"].std()

df["NormalizedOtherPay"] = (df["OtherPay"] - otherPay_mean) / otherPay_std

In [ ]:
df.tail()

Id      EmployeeName                     JobTitle  BasePay  \
148645  148646  Carolyn A Wilson    Human Services Technician      0.0   
148647  148648    Joann Anderson  Communications Dispatcher 2      0.0   
148648  148649       Leon Walker                    Custodian      0.0   
148649  148650     Roy I Tillery                    Custodian      0.0   
148653  148654         Joe Lopez   Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148645          0.0      0.00       0.0      0.00              0.00  2014   
148647          0.0      0.00       0.0      0.00              0.00  2014   
148648          0.0      0.00       0.0      0.00              0.00  2014   
148649          0.0      0.00       0.0      0.00              0.00  2014   
148653          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes            Agency  Status_FT  Status_PT  NormalizedBasePay  \
148645    NaN  b'San Francisco'          0          1            0.00052   
148647    NaN  b'San Francisco'          0          1            0.00052   
148648    NaN  b'San Francisco'          0          1            0.00052   
148649    NaN  b'San Francisco'          0          1            0.00052   
148653    NaN  b'San Francisco'          0          1            0.00052   

        NormalizedOvertimePay  NormalizedOtherPay  
148645           4.079437e-08           -0.454600  
148647           4.079437e-08           -0.454600  
148648           4.079437e-08           -0.454600  
148649           4.079437e-08           -0.454600  
148653           4.079437e-08           -0.531678